"""
Django settings for tutorial project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# === 專案根目錄路徑 ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === 安全設定 ===
SECRET_KEY = 'django-insecure-(&k^==k@ek*tuudtz2!^9rukfpk4e_$3-8d6kxh)l3#dq!c9m('
DEBUG = True
ALLOWED_HOSTS = ["*"]  # 可改為指定 IP 或網域

# === 安裝的 App ===
INSTALLED_APPS = [
    # Django 內建 App
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方套件
    'rest_framework',
    'django_filters',
    'corsheaders',

    # 自訂 App
    'tutorial.todos',
]

# === 中介層設定 ===
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 若有前端連 API，需放最上層
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# === 路由與 WSGI ===
ROOT_URLCONF = 'tutorial.urls'
WSGI_APPLICATION = 'tutorial.wsgi.application'

# === Templates 模板設定 ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# === 資料庫設定（SQLite）===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === 密碼驗證 ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === 語系與時區 ===
LANGUAGE_CODE = 'zh-hant'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_TZ = True

# === 靜態檔案路徑 ===
STATIC_URL = 'static/'

# === 預設主鍵型別 ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Django REST Framework 設定 ===
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ]
}

# === CORS 設定（跨來源允許）===
CORS_ALLOW_ALL_ORIGINS = True  # 如需限制來源可改為 CORS_ALLOWED_ORIGINS = [...]
